### ISSUE TITLE
Questions for v6

### ISSUE THREAD

**Issue by seba9999** [Inqnuam/MongoDB-ARMv8#2]
Hello,

I would like to know if you would like to do the same for mongodb v6 ?

Does this install package would work on a raspberry pi 3B ?

**Comment by seba9999** [comment]
Hello

**Comment by Inqnuam** [comment]
Hello @seba9999 
MongoDB dropped support for ARMv8.1 CPU and older processors.
If im not wrong starting 5.0.7 minium required CPU is ARMv8.2-A or later.
Raspberry Pi 4 and 3 B are both ARMv8 but with different Cortex (A72 and A53)
Have not tested by myself on Raspberry Pi 3 b but did with Pi 4 and it works as excepted

**Comment by seba9999** [comment]
That's so unfortunate !
I've freshly intalled Debian 11 Bullseye 64bit on my raspberry ... And facing some "Illegal Intruction" which I found is linked to incompatible binaries vs CPU :'( 

I really don't know much about "architectures", CPU and "ARMv8.*****" stuff

Which linux distribution are you using on your raspberry 4 ? Does this repository would work on Bullseye ?
Only one way to find out ... I'll try tomorow !

Thanks for your reply !

**Comment by Inqnuam** [comment]
Indeed!
I'm using the official Raspberry Pi Debian 10 Buster (Raspberry Pi OS) 64bit  headless version.
Please let me know if it works on your Pi 3 Bullseye!

**Comment by seba9999** [comment]
Looks like it's working ! Thanks :)

**Comment by Inqnuam** [comment]
Thank you for the update!
